//Idea from https://github.com/bradtraversy/proshop_mern/tree/master/frontend/src/constants

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_GOALS_REQUEST = "USER_GOALS_REQUEST";
export const USER_GOALS_SUCCESS = "USER_GOALS_SUCCESS";
export const USER_GOALS_FAIL = "USER_GOALS_FAIL";

export const USER_UPDATE_GOALS_REQUEST = "USER_UPDATE_GOALS_REQUEST";
export const USER_UPDATE_GOALS_SUCCESS = "USER_UPDATE_GOALS_SUCCESS";
export const USER_UPDATE_GOALS_FAIL = "USER_UPDATE_GOALS_FAIL";
export const USER_UPDATE_GOALS_RESET = "USER_UPDATE_GOALS_RESET";

export const USER_EXERCISES_REQUEST = "USER_EXERCISES_REQUEST";
export const USER_EXERCISES_SUCCESS = "USER_EXERCISES_SUCCESS";
export const USER_EXERCISES_FAIL = "USER_EXERCISES_FAIL";

export const USER_EXERCISES_ID_REQUEST = "USER_EXERCISES_ID_REQUEST";
export const USER_EXERCISES_ID_SUCCESS = "USER_EXERCISES_ID_SUCCESS";
export const USER_EXERCISES_ID_FAIL = "USER_EXERCISES_ID_FAIL";
export const USER_EXERCISES_ID_RESET = "USER_EXERCISES_ID_RESET";

export const USER_EXERCISE_DELETE_REQUEST = "USER_EXERCISE_DELETE_REQUEST";
export const USER_EXERCISE_DELETE_SUCCESS = "USER_EXERCISE_DELETE_SUCCESS";
export const USER_EXERCISE_DELETE_FAIL = "USER_EXERCISE_DELETE_FAIL";

export const USER_EXERCISE_UPDATE_REQUEST = "USER_EXERCISE_UPDATE_REQUEST";
export const USER_EXERCISE_UPDATE_SUCCESS = "USER_EXERCISE_UPDATE_SUCCESS";
export const USER_EXERCISE_UPDATE_FAIL = "USER_EXERCISE_UPDATE_FAIL";
export const USER_EXERCISE_UPDATE_RESET = "USER_EXERCISE_UPDATE_RESET";

export const USER_EXERCISE_CREATE_REQUEST = "USER_EXERCISE_CREATE_REQUEST";
export const USER_EXERCISE_CREATE_SUCCESS = "USER_EXERCISE_CREATE_SUCCESS";
export const USER_EXERCISE_CREATE_FAIL = "USER_EXERCISE_CREATE_FAIL";
export const USER_EXERCISE_CREATE_RESET = "USER_EXERCISE_CREATE_RESET";

export const USER_CONSUMPTION_SEARCH_REQUEST =
  "USER_CONSUMPTION_SEARCH_REQUEST";
export const USER_CONSUMPTION_SEARCH_SUCCESS =
  "USER_CONSUMPTION_SEARCH_SUCCESS";
export const USER_CONSUMPTION_SEARCH_FAIL = "USER_CONSUMPTION_SEARCH_FAIL";
export const USER_CONSUMPTION_SEARCH_RESET = "USER_CONSUMPTION_SEARCH_RESET";

export const USER_CONSUMPTION_ADD_FOOD_REQUEST =
  "USER_CONSUMPTION_ADD_FOOD_REQUEST";
export const USER_CONSUMPTION_ADD_FOOD_SUCCESS =
  "USER_CONSUMPTION_ADD_FOOD_SUCCESS";
export const USER_CONSUMPTION_ADD_FOOD_FAIL = "USER_CONSUMPTION_ADD_FOOD_FAIL";
export const USER_CONSUMPTION_ADD_FOOD_RESET =
  "USER_CONSUMPTION_ADD_FOOD_RESET";

export const USER_GET_CONSUMPTION_REQUEST = "USER_GET_CONSUMPTION_REQUEST";
export const USER_GET_CONSUMPTION_SUCCESS = "USER_GET_CONSUMPTION_SUCCESS";
export const USER_GET_CONSUMPTION_FAIL = "USER_GET_CONSUMPTION_FAIL";
export const USER_GET_CONSUMPTION_RESET = "USER_GET_CONSUMPTION_RESET";

export const USER_DELETE_CONSUMPTION_REQUEST =
  "USER_DELETE_CONSUMPTION_REQUEST";
export const USER_DELETE_CONSUMPTION_SUCCESS =
  "USER_DELETE_CONSUMPTION_SUCCESS";
export const USER_DELETE_CONSUMPTION_FAIL = "USER_DELETE_CONSUMPTION_FAIL";

export const USER_GET_STATISTICS_REQUEST = "USER_GET_STATISTICS_REQUEST";
export const USER_GET_STATISTICS_SUCCESS = "USER_GET_STATISTICS_SUCCESS";
export const USER_GET_STATISTICS_FAIL = "USER_GET_STATISTICS_FAIL";
export const USER_GET_STATISTICS_RESET = "USER_GET_STATISTICS_RESET";
